import { registerEnumType } from '@nestjs/graphql';

export enum ClauseCategory {
  BACKGROUND = 'BACKGROUND',
  SUBJECT_MATTER = 'SUBJECT_MATTER',
  DEFINITIONS = 'DEFINITIONS',
  REPRESENTATIONS = 'REPRESENTATIONS',
  TERM = 'TERM',
  PRICE_AND_PAYMENT = 'PRICE_AND_PAYMENT',
  OBLIGATIONS = 'OBLIGATIONS',
  WARRANTIES = 'WARRANTIES',
  CONFIDENTIALITY = 'CONFIDENTIALITY',
  INTELLECTUAL_PROPERTY = 'INTELLECTUAL_PROPERTY',
  LIABILITY = 'LIABILITY',
  INDEMNIFICATION = 'INDEMNIFICATION',
  TERMINATION = 'TERMINATION',
  FORCE_MAJEURE = 'FORCE_MAJEURE',
  ASSIGNMENT = 'ASSIGNMENT',
  SUBCONTRACTING = 'SUBCONTRACTING',
  INSURANCE = 'INSURANCE',
  LEGAL_COMPLIANCE = 'LEGAL_COMPLIANCE',
  DATA_PROTECTION = 'DATA_PROTECTION',
  EXCLUSIVITY = 'EXCLUSIVITY',
  NON_COMPETE = 'NON_COMPETE',
  DISPUTE_RESOLUTION = 'DISPUTE_RESOLUTION',
  NOTICES = 'NOTICES',
  SCHEDULES = 'SCHEDULES',
  GENERAL_PROVISIONS = 'GENERAL_PROVISIONS',
  OTHER = 'OTHER',
}

registerEnumType(ClauseCategory, { name: 'ClauseCategory' });
